[sl_departures.destination.snowflake.credentials]
database = "TRAFIK_DATA"
username = "DLT_USER"
password = "123456Faze"
host = "FMVXUQS-IF87024.snowflakecomputing.com"
warehouse = "TRAFIK_WH"
role = "ETL_DLT_ROLE"
